export const LOAD_COURSES_SUCCESS = 'LOAD_COURSE';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS';
export const CREATE_COURSES_SUCCESS = 'CREATE_COURSE';
export const UPDATE_AUTHORS_SUCCESS = 'UPDATE_AUTHORS';